### ISSUE TITLE
Debugging a strange issue 

### ISSUE THREAD

**Issue by mlewis-everley** [kinglozzer/silverstripe-mailgunner#10]
I am getting an odd issue with this module and I am unsure how to debug it.

I have a site with this module installed on a Plesk server and it is refusing to send emails (they do not reach their recipient and do not appear in mailgun).

I have created a simple test script using the vanilla mailgun php SDK and this sends emails without issue.

I am using your module on other sites (on a different server) and they send without issue.

There are no errors logged.

I am using PHP 7.0 (have also tried 5.6) with SS 3.6.

Any ideas on what might be happening or how I can debug where this is falling over? It is a very strange issue...

Many thanks,

Mo

**Comment by kinglozzer** [comment]
Possibly a stupid question - have you tried putting the site in dev mode to see if any messages come up? If you set up an `SS_Log` instance, that should log any messages emitted from Mailgun:

```php
SS_Log::add_writer(new SS_LogFileWriter('/var/log/silverstripe/errors.log'), SS_Log::ERR);
```

If that fails, I’d suggest adding breakpoints to `Mailer::sendMessage()` to see at which point it’s failing.

**Comment by mlewis-everley** [comment]
Hi @kinglozzer 

Oddly setting it to dev mode causes the lostpassword form (which I am using to test integration) to time out!

I always forget that SS_Log exists. I set that up and it turns out that the from address was not being set, apparently I omitted the `Email.admin_email` config setting!

If anyone else gets this a similar error, make sure you set `Email.admin_email` in your config!

**Comment by kinglozzer** [comment]
Glad you got it sorted, thanks for posting the solution too - I’ll update the readme!
