### ISSUE TITLE
Send plain results in an empty email  

### ISSUE THREAD

**Issue by mlewis-everley** [kinglozzer/silverstripe-mailgunner#12]
If you send an email in plain text only, as per:

https://docs.silverstripe.org/en/4/developer_guides/email/#sending-plain-text-only

The email sends but with an empty body.

Sending using `Email::send()` however works fine (although it appears that the plain text version of the email is blank).

**Comment by mlewis-everley** [comment]
Hey @kinglozzer 

I have managed to do a quick bit of diagnosis (based on your comments on the slack group). I Did a quick var_dump() of https://github.com/kinglozzer/silverstripe-mailgunner/blob/3.1.0/src/Mailer.php#L126

I tested it on a password reset email and I got this response:

```
// Result of $content:
/home/morven/Projects/adt-store/mailgunner/src/Mailer.php:126:string '<p>Hello Default Admin,</p>

<p>Here is your <a href="http://localhost/adt-store/Security/changepassword?m=1&t=edbe32ba9d40c4f1a8d6a49c699027cd0932e532303ba261b1833faea3c2b5ac6f3a96d94107772d9adcf4143714009d4ef652d155bba3cedb4ec87c0d051fca">password reset link</a> for http://localhost/adt-store/.</p>

' (length=303)

// Result of $plainContent
/home/morven/Projects/adt-store/mailgunner/src/Mailer.php:127:null
```

This shows up in mailgun postbin as:

![mailgun postbin - debug mailgun webhooks](https://user-images.githubusercontent.com/687143/39425090-a1f1d42c-4c71-11e8-9725-e55f2ddb336e.png)

**Comment by mlewis-everley** [comment]
OK, I did some more digging on this, looks like the default mailer checks to see if plaincontent is set before adding it to a html email. If it is not, the HTML content gets converted to plain.

I can fix this by adding the following:

``
if (empty($plainContent)) {
    $plainContent = Convert::xml2raw($content);
}
``

To here: https://github.com/kinglozzer/silverstripe-mailgunner/blob/3.1.0/src/Mailer.php#L177

Results in this:

![mailgun-plain-working](https://user-images.githubusercontent.com/687143/40231892-acec0d76-5a94-11e8-9c03-41a73707752a.png)

**Comment by lozcalver** [comment]
Fixed by https://github.com/kinglozzer/silverstripe-mailgunner/commit/fbb8bd8ed61c2605570d75d5ab5b6073daf4fdf1
