### ISSUE TITLE
Don't throw errors

### ISSUE THREAD

**Issue by dhensby** [kinglozzer/silverstripe-mailgunner#5]
Core mailers don't throw errors in SilverStripe which means core sending of emails or modules won't be wrapping their send calls in `try {} catch` blocks which causes handling of failed sends to... fail.

Instead `return false` to indicate unsent message

**Comment by kinglozzer** [comment]
Good point. Looks like the core `Mailer` returns `false` on a failure, or returns a list of the arguments you provided if successful (https://github.com/silverstripe/silverstripe-framework/blob/master/email/Mailer.php#L163).

That seems completely pointless, but I suppose it’s better to be consistent with that bizarre behaviour...

**Comment by dhensby** [comment]
> That seems completely pointless, but I suppose it’s better to be consistent with that bizarre behaviour...

welcome to SS

**Comment by kinglozzer** [comment]
Closed via https://github.com/kinglozzer/silverstripe-mailgunner/commit/302ea25d6847aa3ec41f3dbda99bc03c3eadb8f7
