### ISSUE TITLE
silent failure on missconfiguration

### ISSUE THREAD

**Issue by alwex** [kinglozzer/silverstripe-mailgunner#7]
in the Mailer class line 130, all exceptions are catch and never re-thrown causing silent error.
```php
        } catch (\Exception $e) {
            // Close and remove any temp files created for attachments, then let the exception bubble up
            $this->closeTempFileHandles();
            return false;
        }
```

Could be a good idea to re throw the exception instead of returning false in the catch block, it will be very useful for debugging purpose.

**Comment by kinglozzer** [comment]
Agreed, unfortunately throwing an exception here breaks SilverStripe’s core `Mailer` API 😞 (see https://github.com/kinglozzer/silverstripe-mailgunner/pull/6).

@dhensby any thoughts on this one? `user_error($e->getMessage(), E_USER_WARNING)` maybe?

**Comment by dhensby** [comment]
I don't think a warning helps too much either - how about just logging it using `SS_Log`?

**Comment by kinglozzer** [comment]
That relies on people setting up a log writer though, and even our installer doesn’t do that. I’m leaning towards raising a warning - it doesn’t need any extra configuration, you can’t miss it unless you develop in live mode, and it should be suppressed in live mode by default.

**Comment by dhensby** [comment]
Doesn't it write to syslog by default?

**Comment by kinglozzer** [comment]
Nope, it doesn’t log anything anywhere unless you set it up 😕. Either way, you’d be completely unaware that you’d done anything wrong unless you happened to check those logs

**Comment by dhensby** [comment]
Yep. Whether you trigger a warning or log the error it will be hidden on a prod server until someone checks. 

This isn't really a problem for this module to solve because it's an issue with how SS mailer works... It never throws any error about whether emails are sent or not. 

Perhaps storing the last exception and allowing devs to access it `$mailer->getLastError()` could be a solution to providing some kind of debugging support?

**Comment by kinglozzer** [comment]
How about this?

```php
if (Director::isDev()) {
    user_error($e->getMessage(), E_USER_ERROR);
} else {
    SS_Log::log($e->getMessage(), SS_Log::ERR);
}
```

So it’s guaranteed to show up in dev mode, and anyone who wants to log errors in test/production envs can do so

**Comment by dhensby** [comment]
Sure.. I don't know how much a dev error would be as I imagine emails probably won't actually be sent on dev??

Maybe I'd log on both and error on dev only...

```php
SS_Log::log($e->getMessage(), SS_Log::ERR);
if (Director::isDev()) {
    user_error($e->getMessage(), E_USER_ERROR);
}
```

Though I'm not really a big fan of such big differences in behaviour on dev vs non-dev

**Comment by dhensby** [comment]
How about `Debug::message()`?

**Comment by kinglozzer** [comment]
Looks good, I’ve gone for that: https://github.com/kinglozzer/silverstripe-mailgunner/commit/87f8e00e156661bbc3ba449d678f890edadb0b22.
