### ISSUE TITLE
Composer Mailgun Version

### ISSUE THREAD

**Issue by joeherbert** [kinglozzer/silverstripe-mailgunner#8]
Is there a good reason that the required version of Mailgun PHP is 1.8?

**Comment by kinglozzer** [comment]
The main reason is that 1.8 was the latest stable version at the time this module was developed. Upgrading to 2.x means dropping PHP 5.4 support, which is fine by me - it’ll just mean a major version bump for this module. I’m not sure if there were any other breaking changes between 1.8 and the latest version, though...

**Comment by nglasl** [comment]
Hi @joeherbert, I noticed that you've forked this and started updating a few things. Would you happen to have an update on how things have been looking?

**Comment by nglasl** [comment]
The problem I'm hitting is that this module uses guzzle ~5.0, however, I have another dependency using guzzle ~6.0. I've pulled your fork down and had a quick play, and this seems to run okay on the latest version (with the few changes you've made). Well, from a simple test anyway. I definitely think it's worth opening a PR @joeherbert :)

**Comment by kinglozzer** [comment]
Okay, I’ve upgraded and tagged [`3.0.0`](https://github.com/kinglozzer/silverstripe-mailgunner/releases/tag/3.0.0). Note that you’ll also need to install an HTTP adapter if you don’t already have one (as per the [install docs](https://github.com/kinglozzer/silverstripe-mailgunner#installation)). Thanks!

**Comment by nglasl** [comment]
Awesome work, @kinglozzer!
